name: The Only Cafe
favicon: null
layout_spectrum: 0.7552090629469603
typography_spectrum: 0.01023646374233067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0225601305719465
  lightness: 0.10451501724310219
  saturation: 0.6708556031808257
  rhythmicContrast: 0.519810103578493
purpose: []
