name: The Only Cafe
favicon: null
layout_spectrum: 0.6481416602618992
typography_spectrum: 0.5216150800697505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4952947741840035
  lightness: 0.48886727006174624
  saturation: 0.09669480449520051
  rhythmicContrast: 0.7642469857819378
purpose: []
